# Change these first
owner: dorulog # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: dorulog.com
    url: https://dorulog.com
#  - name: Wikipedia
#    url: https://en.wikipedia.org


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: dorulog/upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dorulog
  introTitle: "**dorulog** uptime monitor."
  introMessage: dorulog
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
